name: Build and Publish Binary

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          # Build CLI binary
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o intspeed ./cmd/cli
          
          # Build server binary
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o intspeed-server ./cmd/server
          
          # Make binaries executable
          chmod +x intspeed intspeed-server

      - name: Generate SHA512 hashes
        run: |
          sha512sum intspeed > intspeed.sha512
          sha512sum intspeed-server > intspeed-server.sha512

      - name: Import GPG Key
        run: |
          echo "${{ secrets.HQ_ROTKO_PGP }}" | gpg --batch --import
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Configure GPG
        run: |
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye

      - name: Sign binaries and hashes
        run: |
          # Sign CLI binary and hash
          gpg --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --detach-sign --armor --default-key hq@rotko.net --output intspeed.sig intspeed
          gpg --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --detach-sign --armor --default-key hq@rotko.net --output intspeed.sha512.sig intspeed.sha512
          
          # Sign server binary and hash
          gpg --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --detach-sign --armor --default-key hq@rotko.net --output intspeed-server.sig intspeed-server
          gpg --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --detach-sign --armor --default-key hq@rotko.net --output intspeed-server.sha512.sig intspeed-server.sha512

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: intspeed-binaries
          path: |
            intspeed
            intspeed.sig
            intspeed.sha512
            intspeed.sha512.sig
            intspeed-server
            intspeed-server.sig
            intspeed-server.sha512
            intspeed-server.sha512.sig

      - name: Bump version and tag
        id: bump_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          WITH_V: false

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          files: |
            intspeed
            intspeed.sig
            intspeed.sha512
            intspeed.sha512.sig
            intspeed-server
            intspeed-server.sig
            intspeed-server.sha512
            intspeed-server.sha512.sig
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
